### ISSUE TITLE
Seeker is totally broken.

### ISSUE THREAD

**Issue by khallebal** [HaikuArchives/Seeker#24]
Header files were removed but their methods and members were left behind creating a circular include and undeclared methods, i tried to fix the build but it's just too broken.
Anyone knows a copy of it somewhere that still builds?

**Comment by humdingerb** [comment]
You need to install libsanta_devel.
Have a look if it builds after 1fadb5da5b58b79db5d09c601c4cb22ea3e012c6.
It does here with hrev56578+50, 64bit.

**Comment by khallebal** [comment]
Silly me, a newbe mistake, thanks @humdingerb  and sorry for the noise.

**Comment by humdingerb** [comment]
👍  :)
